### ISSUE TITLE
Suggested improvements to the schema

### ISSUE THREAD

**Issue by rly** [focolab/ndx-multichannel-volume#1]
- neurodata_type_def: CElegansSubject -> growth_stage_time attribute -> doc: 
  - Change "ISO duration format" to "ISO 8601 duration format, e.g., P5D = 5 days since the start of the indicated growth stage"
- neurodata_type_def: MultiChannelVolumeSeries -> exposure_time dataset -> doc: 
  - Change "Exposure time of the sample" to "Exposure time of the sample, in seconds"
- neurodata_type_def: OpticalChannelReferences -> data dataset: 
  - In the core NWB schema, the `ImageReferences` data type contains an ordered array of references to `Image` objects. For consistency, using this convention would be preferred. But if you prefer to keep it this way, please update the doc from "Ordered list of optical channels" to "Ordered list of names of the optical channels"

**Comment by dysprague** [comment]
I made the first two changes. I was having some issues changing the OpticalChannelReferences to refer to the object. I kept getting a 'value error: refspec given as type'. Not sure if I'm doing something wrong or if this is a bug, but I submitted an issue on the PYNWB repository

Optimally, I would like this to be an object reference, but keeping it as just the text for now as a stopgap solution.
